server:
  port: ${random.long(999,10000)}
spring:
  application:
    name: cache-test
  redis:
    host: localhost
    port: 6379
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
