name: cadacy analysis CI
on:
  push:
    paths:
      - '**'
      - '!**.md'
      - '!**.yml'
      - '!**.yaml'
    branches:
      - '**'
  pull_request:
    paths:
      - '**'
      - '!**.md'
      - '!**.yml'
      - '!**.yaml'
jobs:
  codacy-analysis-cli:
    name: Codacy Analysis CLI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run Codacy Analysis CLI
        uses: codacy/codacy-analysis-cli-action@1.1.0
        with:
          project-token: ${{secrets.CODACY_PROJECT_TOKEN}}
          verbose: true
          upload: true
          max-allowed-issues: 2147483647
