name: build
on: [ push,pull_request ]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ 1.8 ]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up JDK ${{matrix.java}}
        uses: actions/setup-java@v2
        with:
          java-version: ${{matrix.java}}
      - name:  Cache Maven
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('pom.xml') }}
          restore-keys: ${{ runner.os }}-maven-
      - name: Build with Maven
        run: mvn -B package -DskipTests=true -Dmaven.javadoc.skip=true --file pom.xml
