name: commons CI
on: [push,pull_request]
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Cache Maven
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('pom.xml') }}
          restore-keys: ${{ runner.os }}-maven-
      - name: Build with Maven
        run: mvn -B package -DskipTests=true -Dmaven.javadoc.skip=true --file pom.xml
  codeql:
    runs-on: ubuntu-latest
    needs: check
    strategy:
      fail-fast: false
      matrix:
        language: [ 'java' ]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Cache Maven
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('pom.xml') }}
          restore-keys: ${{ runner.os }}-maven-
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v1
        with:
          languages: java
          config-file: ./.github/codeql/codeql-config.yml
      - name: Build with Maven
        run: mvn clean package -DskipTests=true -Dmaven.javadoc.skip=true -B -V
      - name: codeql-analysis
        uses: github/codeql-action/analyze@v1
  codecov:
    runs-on: ubuntu-latest
    needs: codeql
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Cache Maven
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('pom.xml') }}
          restore-keys: ${{ runner.os }}-maven-
      - name: Build with Maven
        run: |
          mvn clean package -DskipTests=true -Dmaven.javadoc.skip=true -B -V
          mvn cobertura:cobertura -Dcobertura.report.format=xml -Dmaven.javadoc.skip.true -Dorg.slf4j.simpleLogger.defaultLogLevel=error
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
  github-release:
    runs-on: ubuntu-latest
    needs: codecov
    if: ${{contains(github.ref,'tags')}}
    steps:
      - uses: actions/checkout@v2
      - name: Upload Github Release
        uses: meeDamian/github-release@2.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

